language: scala
scala:
   - 2.11.8

jdk:
    - oraclejdk8

before_install:
    - chmod +x gradlew

script:
    - ./gradlew clean build -x itest

after_success:
    - ./gradlew jacocoTestReport coveralls